### ISSUE TITLE
Incomplete instructions on Embed Homewise Product Table - Step 3

### ISSUE THREAD

**Issue by brenoribeirodovalle** [homewise-solutions-inc/developer-guides#3]
Hello,
In the documentation for `Embed Homewise Product Table` - `Step 3`, we're instructed to add a div using a class name following the pattern `homewise_product_table_N`, where N is the position (index) of the configuration in the configuration array (defined in Step 4).

However, step 4 is optional, and if I use `homewise_product_table_0` without going through `Step 4`, the table won't load.

The documentation could state that, if I don't want to go through `Step 4`, then the class name for the div should be `homewise_product_table`. 

This is not a big issue, but will save time if someone is starting to configure/work with the Product Table.

Link: [Embed Homewise Product Table - Step 3](https://github.com/homewise-solutions-inc/developer-guides/blob/master/product_table/embed.md#step-3)

**Comment by mranawake** [comment]
Thanks for comment. We updated the documentation and keeping step #4 as a required step for simplicity. You are accurate about using `homewise_product_table` ID if skipping optional step #4. This behavior will continue to exist, but undocumented.

**Comment by brenoribeirodovalle** [comment]
That makes sense. Thank you for addressing the issue. :)
